# Generated by Django 3.2.8 on 2021-12-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='category',
            field=models.TextField(help_text='Liste des categories auxquelles appartient le film', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='nature',
            field=models.CharField(default='MOVIE', help_text="Classification de l'oeuvre", max_length=50),
        ),
    ]
