# Generated by Django 3.2 on 2021-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('siret', models.CharField(default='', max_length=14)),
                ('address', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='blockchain',
            field=models.CharField(blank=True, default='', help_text='Adresse elrond du profil', max_length=50),
        ),
        migrations.AddField(
            model_name='profil',
            name='school',
            field=models.CharField(blank=True, default='FEMIS', help_text='Ecole', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='dtLastSearch',
            field=models.DateTimeField(default=0, help_text="Date de la dernière recherche d'expérience pour le profil"),
        ),
    ]
