# Generated by Django 4.0.6 on 2022-12-20 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='html',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='article',
            old_name='sumary',
            new_name='summary',
        ),
        migrations.AddField(
            model_name='article',
            name='visual',
            field=models.CharField(default='', help_text="visuel associé à l'article sous forme de lien web", max_length=200),
        ),
    ]
