# Generated by Django 3.2.8 on 2021-11-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20211118_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='department_category',
            field=models.CharField(blank=True, default='', help_text='Categorie de la formation', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='department',
            field=models.CharField(blank=True, default='', help_text='Cursus (pro ou standard) suivi pendant les études', max_length=60, null=True),
        ),
    ]
