# Generated by Django 3.2 on 2021-09-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_auto_20210906_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='reference',
            field=models.CharField(blank=True, default='', help_text="Reference d'oeuvre", max_length=50),
        ),
    ]
