# Generated by Django 4.0.6 on 2023-01-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0002_rename_html_article_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='name_index',
            field=models.CharField(default='', help_text='Index du prenom+nom du profil sans accent, sans espace', max_length=70),
        ),
    ]
