# Generated by Django 3.2.8 on 2021-11-30 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_auto_20211122_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='tags',
            field=models.CharField(default='', help_text='Etiquettes de classification thématique', max_length=100),
        ),
        migrations.AlterField(
            model_name='profil',
            name='acceptSponsor',
            field=models.BooleanField(default=False, help_text='Le profil accepte les demandes de mentorat'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='birthdate',
            field=models.DateField(help_text='Date de naissance du profil', null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='cp',
            field=models.CharField(blank=True, help_text='code postal de résidence', max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='degree_year',
            field=models.IntegerField(help_text="Année de sortie de l'école (promotion)", null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='department_category',
            field=models.CharField(blank=True, default='', help_text='Categorie / code de regroupement de la formation', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='dtLastNotif',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 1, 0, 0), help_text='Date de la dernière notification envoyée'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('A', 'Autre'), ('', 'NSP')], default='M', help_text='Genre du profil', max_length=1),
        ),
        migrations.AlterField(
            model_name='profil',
            name='nationality',
            field=models.CharField(blank=True, default='Française', help_text='Nationnalité du profil', max_length=30),
        ),
        migrations.AlterField(
            model_name='profil',
            name='obsolescenceScore',
            field=models.IntegerField(default=0, help_text="Indique le degré d'obsolescence probable (utilisé pour les relances)"),
        ),
        migrations.AlterField(
            model_name='profil',
            name='sponsorBy',
            field=models.ForeignKey(help_text='Nom du mentor', null=True, on_delete=django.db.models.deletion.CASCADE, to='alumni.profil'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='tiktok',
            field=models.URLField(blank=True, help_text='Adresse de la page tiktok du profil', null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='town',
            field=models.CharField(blank=True, help_text="Ville de l'adresse postale de résidence", max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='vimeo',
            field=models.URLField(blank=True, help_text='Adresse de la page vimeo du profil', null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='website',
            field=models.URLField(blank=True, default='', help_text='Site web du profil', null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='youtube',
            field=models.URLField(blank=True, help_text='Adresse de la page youtube du profil', null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='comment',
            field=models.TextField(blank=True, default='', help_text="Commentaire libre sur la façon dont s'est passé le travail", max_length=400),
        ),
        migrations.AlterField(
            model_name='work',
            name='creator',
            field=models.CharField(default='auto', help_text="Désigne qui est le dernier auteur de l'enregistrement du travail dans la base de données", max_length=5),
        ),
        migrations.AlterField(
            model_name='work',
            name='duration',
            field=models.IntegerField(default=0, help_text='Durée du travail en heure'),
        ),
        migrations.AlterField(
            model_name='work',
            name='job',
            field=models.CharField(default='', help_text='Désignation du travail réalisé', max_length=200),
        ),
        migrations.AlterField(
            model_name='work',
            name='pow',
            field=models.ForeignKey(help_text='Oeuvre concernée par le travail', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='alumni.pieceofwork'),
        ),
        migrations.AlterField(
            model_name='work',
            name='profil',
            field=models.ForeignKey(help_text='Profil ayant réalisé le travail', on_delete=django.db.models.deletion.CASCADE, related_name='works', to='alumni.profil'),
        ),
        migrations.AlterField(
            model_name='work',
            name='source',
            field=models.CharField(default='', help_text="source ayant permis d'identifier le projet : imdb, unifrance, lefilmfrancais, bellefaye, manuel", max_length=100),
        ),
    ]
