# Generated by Django 3.2 on 2021-09-21 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_pieceofwork_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='pieceofwork',
            name='dtLastSearch',
            field=models.DateField(default=0, help_text="Date de dernière recherche sur l'oeuvre"),
        ),
    ]
