# Generated by Django 4.0.6 on 2023-06-08 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0003_alter_profil_name_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='ask',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
