# Generated by Django 4.0.6 on 2023-06-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_extrauser_ask'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrauser',
            name='ask',
            field=models.CharField(blank=True, default='', max_length=20, null=True),
        ),
    ]
