# Generated by Django 3.2.8 on 2021-12-07 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0004_alter_profil_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='sans titre', help_text='Nom du festival', max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='sans titre', help_text='Nom du festival', max_length=100, unique=True)),
                ('year', models.IntegerField(help_text='Date de la remise du prix')),
                ('pow', models.ForeignKey(help_text='Oeuvre récompensé', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='alumni.pieceofwork')),
                ('profil', models.ForeignKey(help_text='Profil destinataire du prix', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='award', to='alumni.profil')),
            ],
        ),
    ]
