# Generated by Django 3.2 on 2021-09-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_profil_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profil',
            name='company',
        ),
    ]
