# Generated by Django 3.2.8 on 2021-12-07 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0005_award_festival'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='festival',
            field=models.ForeignKey(help_text='Festival correspondant', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', to='alumni.festival'),
        ),
    ]
