# Generated by Django 3.2 on 2021-09-21 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0006_remove_profil_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtLastSearch',
            field=models.DateField(default=0, help_text="Date de la derniere recherche automatique sur l'oeuvre"),
        ),
    ]
