# Generated by Django 3.2.8 on 2021-12-07 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alter_award_pow'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(default='sans titre', help_text='Nom du festival', max_length=100),
        ),
    ]
