# Generated by Django 3.2 on 2021-09-21 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_alter_pieceofwork_dtlastsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtLastSearch',
            field=models.DateTimeField(default=0, help_text="Date de la derniere recherche automatique sur l'oeuvre"),
        ),
    ]
