# Generated by Django 4.0.6 on 2023-07-13 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0007_profil_department_pro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='production',
            field=models.CharField(blank=True, default='', help_text="Production de l'oeuvre", max_length=200),
        ),
    ]
