# Generated by Django 3.2 on 2021-09-29 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_pieceofwork_dtlastsearch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='cp',
            field=models.CharField(blank=True, help_text='code postal', max_length=5, null=True),
        ),
    ]
