# Generated by Django 3.2.8 on 2021-12-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_award_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='title',
            field=models.CharField(default='sans titre', help_text="Titre de l'oeuvre, même temporaire", max_length=300),
        ),
    ]
