# Generated by Django 4.0.6 on 2023-07-14 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0008_alter_pieceofwork_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='cursus',
            field=models.CharField(blank=True, choices=[('S', 'Standard'), ('P', 'Professionnel')], default='S', help_text='Type de formation', max_length=1),
        ),
    ]
