# Generated by Django 3.2.8 on 2021-10-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_profil_cp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='dtLastNotif',
            field=models.DateTimeField(default=0, help_text='Date de la dernière notification envoyé'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
