# Generated by Django 4.0.6 on 2023-09-21 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_profil_cursus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='department',
            field=models.CharField(blank=True, default='', help_text='département formation initiale suivi pendant les études', max_length=60, null=True),
        ),
    ]
