# Generated by Django 3.2.8 on 2021-12-16 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0009_alter_pieceofwork_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.CharField(blank=True, default='sans titre', help_text='Nom du festival', max_length=250),
        ),
        migrations.AlterField(
            model_name='award',
            name='year',
            field=models.IntegerField(help_text='Date de la remise du prix', null=True),
        ),
    ]
