# Generated by Django 3.2.8 on 2021-10-14 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0010_auto_20211014_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profil',
            name='advices',
            field=models.JSONField(default=None, help_text="Liste de conseils alimenter par l'outil pour augmenter le rayonnement d'une personne", null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='biography',
            field=models.TextField(default='', help_text='Biographie du profil', max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='country',
            field=models.CharField(blank=True, default='France', help_text='Pays de naissance', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profil',
            name='photo',
            field=models.TextField(blank=True, default='/assets/img/anonymous.png', help_text='Photo du profil au format Base64'),
        ),
        migrations.AlterField(
            model_name='profil',
            name='website',
            field=models.URLField(blank=True, default='', null=True),
        ),
    ]
