# Generated by Django 3.2.8 on 2022-01-03 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0011_training'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='dtCreate',
            field=models.DateField(auto_now_add=True, help_text="Date d'enregistrement de la contribution", null=True),
        ),
    ]
