# Generated by Django 3.2.8 on 2022-01-04 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_work_dtcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='dtCreate',
            field=models.DateField(auto_now=True, help_text="Date de création de l'article", null=True),
        ),
    ]
