# Generated by Django 3.2.8 on 2021-10-20 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0012_auto_20211014_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pieceofwork',
            name='dtLastSearch',
            field=models.DateTimeField(auto_now_add=True, help_text="Date de la derniere recherche automatique sur l'oeuvre"),
        ),
    ]
