# Generated by Django 3.2.8 on 2021-11-03 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_alter_pieceofwork_dtlastsearch'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='public_photo',
            field=models.BooleanField(default=False, help_text='Indique si la photo peut être ou pas présentée sur la page publique'),
        ),
    ]
