# Generated by Django 3.2.8 on 2022-01-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0013_award_dtcreate'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='winner',
            field=models.BooleanField(default=True, help_text="Indique s'il s'agit d'une nomination ou d'une victoire"),
        ),
        migrations.AddField(
            model_name='festival',
            name='country',
            field=models.CharField(help_text='Pays du festival', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='dtCreate',
            field=models.DateField(auto_now=True, help_text="Date de création de l'article", null=True),
        ),
        migrations.AddField(
            model_name='festival',
            name='url',
            field=models.CharField(blank=True, default='', help_text="URL de la page d'acceuil du festival", max_length=150),
        ),
    ]
