# Generated by Django 3.2.8 on 2022-01-13 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0015_pieceofwork_title_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='name_index',
            field=models.CharField(default='', help_text='Index du nomprenom du profil', max_length=70),
        ),
        migrations.AlterField(
            model_name='pieceofwork',
            name='description',
            field=models.TextField(default='', help_text="Synopsis/Description/Résumé de l'oeuvre", max_length=3000),
        ),
    ]
