# Generated by Django 3.2.8 on 2022-01-20 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0016_auto_20220113_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='state',
            field=models.CharField(default='A', help_text='etat du travail entre A=automatiquement creer,E=editer par le profil, D=supprimé par le profil', max_length=1),
        ),
    ]
