# Generated by Django 3.2.8 on 2022-01-26 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0019_auto_20220126_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='html',
            field=models.TextField(blank=True, default='', help_text="Contenu de l'article"),
        ),
    ]
