# Generated by Django 3.2.8 on 2022-01-31 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0020_alter_article_html'),
    ]

    operations = [
        migrations.AddField(
            model_name='profil',
            name='crm',
            field=models.URLField(blank=True, help_text="Lien avec l'outil de CRM", null=True),
        ),
    ]
