# Generated by Django 4.0.2 on 2022-03-18 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0021_profil_crm'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.TextField(blank=True, help_text='Titre du sondage', max_length=50)),
                ('description', models.TextField(blank=True, help_text="Description / message d'intro pour les profils", max_length=200)),
                ('html', models.TextField(blank=True, help_text='Code ou URL du sondage', max_length=200)),
                ('dtCreate', models.DateField(auto_now_add=True, help_text='Date de création du sondage')),
                ('dtStart', models.DateField(auto_now_add=True, help_text="Date de début d'apparition du sondage")),
                ('dtEnd', models.DateField(auto_now_add=True, help_text='Date de fin du sondage')),
            ],
        ),
        migrations.AddField(
            model_name='profil',
            name='allocine',
            field=models.URLField(blank=True, help_text='Adresse de la page sur allocine', null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='imdb',
            field=models.URLField(blank=True, help_text='Adresse de la page sur imdb', null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='unifrance',
            field=models.URLField(blank=True, help_text='Adresse de la page sur unifrance', null=True),
        ),
        migrations.AddField(
            model_name='profil',
            name='wikipedia',
            field=models.URLField(blank=True, help_text='Adresse de la page sur wikipedia', null=True),
        ),
    ]
