# Generated by Django 4.0.2 on 2022-03-28 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0022_survey_profil_allocine_profil_imdb_profil_unifrance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrauser',
            name='dtCreate',
            field=models.DateField(auto_now_add=True, help_text='Date de creation du compte', null=True),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='dtLogin',
            field=models.DateField(blank=True, help_text='Date de la dernière connexion', null=True),
        ),
        migrations.AddField(
            model_name='extrauser',
            name='nbLogin',
            field=models.IntegerField(default=0, help_text='Nombre de connexions'),
        ),
    ]
