# Generated by Django 4.0.2 on 2022-05-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0023_extrauser_dtcreate_extrauser_dtlogin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profil',
            options={'ordering': ['lastname', 'degree_year']},
        ),
    ]
