# Generated by Django 4.0.2 on 2022-06-01 09:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0025_alter_award_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='dtCreate',
            field=models.DateField(auto_now=True, help_text='Date de référencement du prix dans DataCulture', null=True),
        ),
        migrations.AlterField(
            model_name='award',
            name='festival',
            field=models.ForeignKey(help_text='Festival correspondant au prix reçu', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='award', to='alumni.festival'),
        ),
    ]
