# Generated by Django 4.0.2 on 2022-06-28 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alumni', '0027_alter_pieceofwork_dtcreate_alter_pieceofwork_nature_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='score_salary',
            field=models.IntegerField(default=None, help_text="Votre revenu correspondait t'il à vos attentes (1-4)", null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='score_school',
            field=models.IntegerField(default=None, help_text="La formation à la FEMIS vous a t'elle aidé pour ce travail (1-4)", null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='score_skill',
            field=models.IntegerField(default=None, help_text="Vous sentez vous a l'aise pour ce travail (1-4)", null=True),
        ),
    ]
