version: 1
appname: "Data Culture Pro"
anonymousOffer: 0

profil_code: hh4271

search:
  limit: 50

catalog:
  imdb: true
  lefilmfrancais: false
  unifrance: true
  senscritique: false

support:
  forum: "http://kerberus.les-forums.com/"
  email: "contact@f80.fr"
  facebook: "https://www.facebook.com/kerberus/"
  faq: "./faq.html?from=appli"
  website: ""

editor:
  name: "F80"
  website: "https://f80.fr"
  author:
    - "Hervé HOAREAU"
    - "Jérôme LECANU"
  link_author:
    - "https://www.linkedin.com/in/hhoareau/"
    - "https://www.linkedin.com/in/jlecanu/"
  contact: "herve.hoareau@f80.fr"


users:
  admins:
    - "hhoareau@gmail.com"
    - "j.lecanu@femis.fr"
    - "paul.dudule@gmail.com"
    - "roger.legumes@gmail.com"
