version: '3'

services:
  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_SMTP_ENABLED=true
      - GF_SMTP_HOST=smtp.example.com
      - GF_SMTP_USER=myuser
      - GF_SMTP_PASSWORD=mysecret
    volumes:
      - grafana-storage:/var/lib/grafana
    ports:
      - 3000:3000

volumes:
  grafana-storage: